name: CI Workflow

# Triggers the workflow on push or pull request to main or master branch
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

# Specify the job(s) for this workflow
jobs:
  build:
    # The type of runner to use for the job
    runs-on: ubuntu-latest

    # Steps for the job
    steps:
      # Step 1: Check out the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: "17"

      # Step 3: Build the project with Maven
      - name: Build with Maven
        run: ./mvnw clean install

      # Step 4: Run tests
      - name: Run tests
        run: ./mvnw test
